### ISSUE TITLE
Sentry Issue: Validation Error on Fact Cookies webpage

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/digital-land.info#318]
**Overview**

Sentry has noticed an unhandled Validation Error on the Fact Cookies URL. Full details can be found on the [relevant Sentry webpage](https://planning-data-platform.sentry.io/issues/4908706043/?project=4506540992626688&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1 "‌") - it looks like the string being received is not within the agreed regex.

**Tech Approach**

- ‌

**Acceptance Criteria/Tests**

- Upon being fixed, the Sentry record should show no events for this error.

**Resourcing**
Consumers tickets are judged to be a low priority unless the number of events of the error becomes substantial and so causes a major client-facing issue.

**Comment by feba-rajan** [comment]
PR: https://github.com/digital-land/digital-land.info/pull/317
